site_name: Template mkdocs-material
dev_addr: 0.0.0.0:11001
theme:
  name: material
  palette:
    scheme: preference
    primary: teal
    accent: indigo
nav:
  - Home: ../README.md
  - Template Reference: index.md
  - Template About: about.md
