site_name: Template site
dev_addr: 0.0.0.0:11001
repo_url: https://github.com/nah-a/mkdocs-material-template/

theme:
  name: material

  # Default values, taken from mkdocs_theme.yml
  language: en

  features:
    - tabs

  palette:
    scheme: preference
    primary: teal
    accent: indigo

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.abbr
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Notes:
    - Markdown cheat-sheets: cheatsheet.md 
    - Docker security tips: docker-security.md
