site_name: Template mkdocs-material
dev_addr: 0.0.0.0:11001
repo_url: https://github.com/nah-a/mkdocs-material-template/
theme:
  name: material
  palette:
    scheme: preference
    primary: teal
    accent: indigo
nav:
  - Welcome to material-mkdocs: index.md
  - Some markdown cheat-sheets: cheatsheet.md 
  - Docker security basics: docker-security.md
