site_name: Template site
dev_addr: 0.0.0.0:11001
repo_url: https://github.com/nah-a/mkdocs-material-template/

theme:
  name: material

  # Default values, taken from mkdocs_theme.yml
  language: en

  features:
    - tabs

  palette:
    scheme: preference
    primary: teal
    accent: indigo

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde

nav:
  - Home: index.md
  - Notes:
    - Markdown cheat-sheets: cheatsheet.md 
    - Docker security tips: docker-security.md

